#!/bin/sh

ENABLED=yes
PROCS=satpi
ARGS="--http-path /opt/share/satpi/web --http-port 8875"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/opt/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
